### ISSUE TITLE
redundant folder structure

### ISSUE THREAD

**Issue by ssahara** [hokkaidoperson/DokuWiki-Ruby-Plugin#1]
レポジトリ内トップの ruby フォルダが冗長です。
この構成でも Extention Managerで正常にインストールできますが、
DokuWiki-OnlineNumber-Plugin のようなフォルダ構成にして欲しいです。

**Comment by hokkaidoperson** [comment]
I changed the folder structure.
(I published the plugin for the first time, so I didn't know about it well.

**Comment by ssahara** [comment]
Thanks!

**Comment by hokkaidoperson** [comment]
（別に日本語で返答してもよかったと今気付いた）
